config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root to: 'categories#index'

  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  has_many :tasks, dependent: :destroy
  validates :name, presence: :true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :task_name, presence: :true
  validates :due_date, presence: :true

  scope :due_today, -> { where(due_date: Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.all
    @tasks_due_today = current_user.tasks.due_today.joins(:category)
  end

  def show
    @tasks = @category.tasks
    @task = Task.new
  end

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy!
      redirect_to @category
    else
      render :index
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to '/'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category
  before_action :set_task, only: %i[edit update destroy]

  def show
    redirect_to category_path(@category)
  end

  def new
    @task = @category.tasks.new
  end

  def create
    @task = @category.tasks.new(task_params)
    if @task.save
      redirect_to category_path(@category), notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to category_path(@category), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to category_path(@task.category), notice: 'Task was successfully deleted.'
    else
      render :index
    end
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :due_date)
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to '/'
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="p-4 mt-16 flex flex-1 items-start justify-center ">
  <%= form_with model: @category do |form| %>
  <div class="flex flex-col gap-4 border rounded-md p-10 justify-center items-center bg-slate-900 text-white">
    <%= form.label "Category name:" %>
    <%= form.text_field :name, class: "text-black" %>
    <%= form.button class: "p-3 bg-green-700 rounded-md"%>
    </div>
  <% end %>
</div>

app/views/categories/_navbar.html.erb
  <div class="flex p-7 justify-between items-center bg-white text-black"> 
    
    <h1 class="text-4xl font-bold"> <%= link_to "jrnl.", root_path %>  </h1>
///
  <div class="flex gap-5">
    <%= link_to "Create a category", new_category_path, class: "font-bold text-md" %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "font-bold text-md"  %>
  </div>
  </div>

app/views/categories/edit.html.erb
<div class="bg-slate-900 text-white min-h-screen flex flex-col p-4 justify-center items-center">
  <h1>Edit category</h1>


<%= form_with model: @category, url: category_path(@category), method: :patch do |form| %>
<div class="flex flex-col w-fit">
  <%= form.label :name %>
  <%= form.text_field :name, class: "text-black" %>
  <%= form.submit :Edit, class: "border bg-green-500 p-3 rounded-md mt-2" %>
  </div>
<% end %>
</div>

app/views/categories/index.html.erb
<div class="flex flex-col h-screen">

  <%= render partial: 'navbar' %>

  <div class="flex flex-1 justify-start items-center text-white">
    <div class="border border-t-4 h-full w-2/5 bg-slate-900 p-7 flex flex-col">
      <h2 class="text-4xl font-bold mb-8"> Categories. </h2>
      <% @categories.each do |category| %>
       <li dir="ltr" class=" rounded-md font-bold text-lg my-4 ps-4 py-4 hover:bg-slate-800 cursor-pointer"> <%= link_to category.name.capitalize, category_path(category) %> </li>
      <% end %>
    </div>

    <div class="border border-t-4 h-full w-3/5 bg-slate-900 p-7 flex flex-col">
      <h2 class="text-4xl font-bold mb-8"> Here are your tasks today, <%= current_user.email.split('@').first.capitalize %>. </h2>
        <% @tasks_due_today.each do |task| %>
         <span dir="ltr" class="my-4 ps-4 py-4 hover:bg-slate-800 cursor-pointer"> <%= task.task_name.capitalize %> </span> 
        <% end %>
    </div>
  </div>

</div>

app/views/categories/new.html.erb
<div class="flex flex-col bg-slate-900 min-h-screen">
  <%= render partial: 'navbar' %>
  <%= render partial: 'form'  %>
</div>

app/views/categories/show.html.erb
<div class="flex flex-col flex-1 bg-slate-900 min-h-screen text-white">

<div class="flex justify-between items-center p-6 ">
<span><%=link_to @category.name.capitalize, categories_path, class: "font-bold text-4xl" %></span>

  
    <%= form_with model: [@category, @task] do |form| %>
      <%= form.label "Add task:" %>
      <%= form.text_field :task_name, class: "text-black"%>

      <%= form.label "Due Date:" %>
      <%= form.date_field :due_date, class: "text-black"%>
      
      <%= form.submit class: "rounded-lg py-2 px-5 bg-white text-black inline-block font-medium cursor-pointer" %> 
    <% end %>
 
  <div class="flex gap-4">
    <%= link_to "Back to Home", categories_path %>
    <%= link_to "Edit Category", edit_category_path %>
    <%= button_to "Delete Category", category_path(@category), method: :delete %>
  </div>
</div>


  <div class="flex flex-1 flex-col border border-white p-4 h-screen gap-6 overflow-y-auto">
    <% @category.tasks.each do |task| %>
        <div class="flex justify-between border border-white p-6">
          <%= task.task_name  %>
          <div class="flex gap-4">
          <%= link_to "Edit", edit_category_task_path(@category, task) %>
          <%= button_to "Completed", category_task_path(@category, task), method: :delete %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jrnl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen w-screen">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
    <%= form.label :task_name %>
    <%= form.text_field :task_name, 
    class: "text-black block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
 
 <% end %> 
 

app/views/tasks/edit.html.erb
<div class="bg-slate-900 text-white min-h-screen flex flex-col p-4">
  <h1 class="font-bold text-3xl p-5 mb-2">Edit task</h1>

<%= form_with model: @task, url: category_task_path(@category, @task), method: :patch do |form| %>
<div class="flex flex-col gap-4 border rounded-md p-8 justify-start items-start bg-slate-900 text-white"">
  <%= form.label :task_name %>
  <%= form.text_field :task_name, class: "text-black w-1/4"%>
  
  <%= form.label :due_date %>
  <%= form.date_field :due_date, class: "text-black w-1/4" %>

  <%= form.submit :Edit, class: "text-white p-4 border rounded-md bg-green-700 w-1/4" %>
<% end %>
  <%= button_to "Delete", category_task_path(@category, @task), method: :delete, class: "text-white p-4 border rounded-md bg-red-700 w-100" %>
</div>
</div>

app/views/tasks/new.html.erb
yo 